### ISSUE TITLE
Unable to run visidata from R

### ISSUE THREAD

**Issue by rbratslaver** [paulklemm/rvisidata#10]
Hi - thanks for making this package! I'm trying to give it a go, wondering if you know what might be causing this. 

```
> library(rvisidata)
> rvisidata::vd(iris)
Loading required package: jsonlite
Warning message:
In system2(vd_cmd, args = temp_file) : '"vd"' not found
```

I suspect it's related to the below and my install of visidata. I can open visidata by typing "visidata" in the command line, but not through the `vd filename.csv` method on Windows.
```
>vd --version
'vd' is not recognized as an internal or external command,
operable program or batch file.
```

Thanks for any help on this!

**Comment by paulklemm** [comment]
You need to have `visidata` in your local environment. Here is how you install it: https://www.visidata.org/install/
