### ISSUE TITLE
Refactor Request: Remove non-vital dependencies

### ISSUE THREAD

**Issue by mstr3336** [paulklemm/rvisidata#2]
Hi - 
I work in a lot of remote ssh sessions, usually from the R console, and I'm interested in exploring visidata for a nicer way to view data.
I'd like to use your package, but I do wonder if the dependencies on magrittr and readr are necessary, given the minimalism of the codebase. 

I also enjoy `magrittr` syntax, and the `readr` interface over base R, but for a package this small, I wonder if we could tolerate eliminating all non-base dependencies and forgoing the pipe? Thanks :)

**Comment by paulklemm** [comment]
Hi there. Thanks for the suggestion. Done.
