### ISSUE TITLE
Optionally prefer to use jsonlite for serialization over write.csv

### ISSUE THREAD

**Issue by mstr3336** [paulklemm/rvisidata#5]
Hi, 
I'd like to use `jsonlite::write_json` for serializing dataframes over the older, less flexible and less standardized `csv`. 

My motivation is that there's `write.csv` is unable to serialize list columns and other more complex datastructures

I think it could be made an optional dependency, allowing a fallback to base R if the package isn't available. 

I've implemented it on a branch on my fork, but it's built on another upstream branch that adds tmux integration ( #4 ), so I'll put in the PR, but that's under the assumption that you accept my first PR. 

I can base this on your master if you reject #4 .

**Comment by paulklemm** [comment]
Great contribution, merged PR into master.
